version: '3'

networks:
  laravel:

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
        # site-api.com:
      - ./sites/site-api.com/:/var/www/site-api.com
        # site-web.com:
      - ./sites/site-web.com/:/var/www/site-web.com
    networks:
      - laravel

  nginx:
    build:
      context: ./docker/nginx
    volumes:
        #Nginx Global Configurations
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        # site-api.com:
        # - Nginx Server block
      - ./docker/nginx/sites-available/site-api.com.conf:/etc/nginx/sites-available/site-api.com.conf
        # - Public Folder:
      - ./sites/site-api.com/:/var/www/site-api.com

        # site-web.com:
        # - Nginx Server block
      - ./docker/nginx/sites-available/site-web.com.conf:/etc/nginx/sites-available/site-web.com.conf
        # - Public Folder:
      - ./sites/site-web.com/:/var/www/site-web.com
    ports:
      - "80:80"
      #- "443:443"
    depends_on:
      - php-fpm
      - mysql_bks
    restart: always
    networks:
      - laravel
  
  mysql_bks:
    platform: linux/amd64
    image: mysql:5.7.29
    container_name: mysql_bks
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      MYSQL_ROOT_PASSWORD: root@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_bks
    networks:
      - laravel
