version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
        # site-one.com:
      - ./sites/site-one.com/laravel/:/var/www/site-one.com
        # site-two.com:
      - ./sites/site-two.com/laravel/:/var/www/site-two.com

  nginx:
    build:
      context: ./docker/nginx
    volumes:
        #Nginx Global Configurations
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        # site-one.com:
        # - Nginx Server block
      - ./sites/site-one.com/site.conf:/etc/nginx/sites-available/site-one.com.conf
        # - Public Folder:
      - ./sites/site-one.com/laravel/:/var/www/site-one.com

        # site-two.com:
        # - Nginx Server block
      - ./sites/site-two.com/site.conf:/etc/nginx/sites-available/site-two.com.conf
        # - Public Folder:
      - ./sites/site-two.com/laravel/:/var/www/site-two.com
    ports:
      - "80:80"
      #- "443:443"
    depends_on:
      - php-fpm
    restart: always
